# Generated by Django 6.0.1 on 2026-01-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='user/photos/default.jpg', upload_to='profile_pics'),
        ),
    ]
