# Generated by Django 6.0.1 on 2026-02-07 14:55

import web.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='user/photos/default.jpg', upload_to=web.models.user.photo_upload_to),
        ),
    ]
