# Generated by Django 6.0.2 on 2026-03-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_systemprompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='updated_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='updated_time',
            new_name='update_time',
        ),
    ]
