# Generated by Django 6.0.2 on 2026-03-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_updated_time_character_update_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='created_time',
            new_name='create_time',
        ),
    ]
